name: Deploy website
on:
  push:
    branches:
      - main
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
      css-name: ${{ steps.cssFileName.outputs.css-name }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Publish the JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Get the css file name
        id: cssFileName
        run: find dist/assets/*.css -type f -execdir echo 'css-name={}' >> $GITHUB_OUTPUT ';'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7 
        with:
          name: dist-test
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v7
        with:
          name: dist-test
      - name: Output filename
        run: |
          OUTPUT1=${{ needs.build.outputs.script-file }}
          OUTPUT2=${{ needs.build.outputs.css-name }}
          echo "$OUTPUT1 and $OUTPUT2"
      - name: Deploy
        run: echo "Deploying..."
